use crate::gl;
use glfw::Key;
use std::mem;
/// Input keys.
#[repr(i32)]
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
pub enum StringKey {
    Space,
    Apostrophe,
    Comma,
    Minus,
    Period,
    Slash,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Semicolon,
    Equal,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    LeftBracket,
    Backslash,
    RightBracket,
    GraveAccent,
    World1,
    World2,
    Escape,
    Enter,
    Tab,
    Backspace,
    Insert,
    Delete,
    Right,
    Left,
    Down,
    Up,
    PageUp,
    PageDown,
    Home,
    End,
    CapsLock,
    ScrollLock,
    NumLock,
    PrintScreen,
    Pause,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDecimal,
    KpDivide,
    KpMultiply,
    KpSubtract,
    KpAdd,
    KpEnter,
    KpEqual,
    LeftShift,
    LeftControl,
    LeftAlt,
    LeftSuper,
    RightShift,
    RightControl,
    RightAlt,
    RightSuper,
    Menu,
    Unknown,
}

impl From<Key> for StringKey {
    fn from(key: glfw::Key) -> StringKey {
        match key {
            Key::Space => StringKey::Space,
            Key::Apostrophe => StringKey::Apostrophe,
            Key::Comma => StringKey::Comma,
            Key::Minus => StringKey::Minus,
            Key::Period => StringKey::Period,
            Key::Slash => StringKey::Slash,
            Key::Num0 => StringKey::Num0,
            Key::Num1 => StringKey::Num1,
            Key::Num2 => StringKey::Num2,
            Key::Num3 => StringKey::Num3,
            Key::Num4 => StringKey::Num4,
            Key::Num5 => StringKey::Num5,
            Key::Num6 => StringKey::Num6,
            Key::Num7 => StringKey::Num7,
            Key::Num8 => StringKey::Num8,
            Key::Num9 => StringKey::Num9,
            Key::Semicolon => StringKey::Semicolon,
            Key::Equal => StringKey::Equal,
            Key::A => StringKey::A,
            Key::B => StringKey::B,
            Key::C => StringKey::C,
            Key::D => StringKey::D,
            Key::E => StringKey::E,
            Key::F => StringKey::F,
            Key::G => StringKey::G,
            Key::H => StringKey::H,
            Key::I => StringKey::I,
            Key::J => StringKey::J,
            Key::K => StringKey::K,
            Key::L => StringKey::L,
            Key::M => StringKey::M,
            Key::N => StringKey::N,
            Key::O => StringKey::O,
            Key::P => StringKey::P,
            Key::Q => StringKey::Q,
            Key::R => StringKey::R,
            Key::S => StringKey::S,
            Key::T => StringKey::T,
            Key::U => StringKey::U,
            Key::V => StringKey::V,
            Key::W => StringKey::W,
            Key::X => StringKey::X,
            Key::Y => StringKey::Y,
            Key::Z => StringKey::Z,
            Key::LeftBracket => StringKey::LeftBracket,
            Key::Backslash => StringKey::Backslash,
            Key::RightBracket => StringKey::RightBracket,
            Key::GraveAccent => StringKey::GraveAccent,
            Key::World1 => StringKey::World1,
            Key::World2 => StringKey::World2,
            Key::Escape => StringKey::Escape,
            Key::Enter => StringKey::Enter,
            Key::Tab => StringKey::Tab,
            Key::Backspace => StringKey::Backspace,
            Key::Insert => StringKey::Insert,
            Key::Delete => StringKey::Delete,
            Key::Right => StringKey::Right,
            Key::Left => StringKey::Left,
            Key::Down => StringKey::Down,
            Key::Up => StringKey::Up,
            Key::PageUp => StringKey::PageUp,
            Key::PageDown => StringKey::PageDown,
            Key::Home => StringKey::Home,
            Key::End => StringKey::End,
            Key::CapsLock => StringKey::CapsLock,
            Key::ScrollLock => StringKey::ScrollLock,
            Key::NumLock => StringKey::NumLock,
            Key::PrintScreen => StringKey::PrintScreen,
            Key::Pause => StringKey::Pause,
            Key::F1 => StringKey::F1,
            Key::F2 => StringKey::F2,
            Key::F3 => StringKey::F3,
            Key::F4 => StringKey::F4,
            Key::F5 => StringKey::F5,
            Key::F6 => StringKey::F6,
            Key::F7 => StringKey::F7,
            Key::F8 => StringKey::F8,
            Key::F9 => StringKey::F9,
            Key::F10 => StringKey::F10,
            Key::F11 => StringKey::F11,
            Key::F12 => StringKey::F12,
            Key::F13 => StringKey::F13,
            Key::F14 => StringKey::F14,
            Key::F15 => StringKey::F15,
            Key::F16 => StringKey::F16,
            Key::F17 => StringKey::F17,
            Key::F18 => StringKey::F18,
            Key::F19 => StringKey::F19,
            Key::F20 => StringKey::F20,
            Key::F21 => StringKey::F21,
            Key::F22 => StringKey::F22,
            Key::F23 => StringKey::F23,
            Key::F24 => StringKey::F24,
            Key::F25 => StringKey::F25,
            Key::Kp0 => StringKey::Kp0,
            Key::Kp1 => StringKey::Kp1,
            Key::Kp2 => StringKey::Kp2,
            Key::Kp3 => StringKey::Kp3,
            Key::Kp4 => StringKey::Kp4,
            Key::Kp5 => StringKey::Kp5,
            Key::Kp6 => StringKey::Kp6,
            Key::Kp7 => StringKey::Kp7,
            Key::Kp8 => StringKey::Kp8,
            Key::Kp9 => StringKey::Kp9,
            Key::KpDecimal => StringKey::KpDecimal,
            Key::KpDivide => StringKey::KpDivide,
            Key::KpMultiply => StringKey::KpMultiply,
            Key::KpSubtract => StringKey::KpSubtract,
            Key::KpAdd => StringKey::KpAdd,
            Key::KpEnter => StringKey::KpEnter,
            Key::KpEqual => StringKey::KpEqual,
            Key::LeftShift => StringKey::LeftShift,
            Key::LeftControl => StringKey::LeftControl,
            Key::LeftAlt => StringKey::LeftAlt,
            Key::LeftSuper => StringKey::LeftSuper,
            Key::RightShift => StringKey::RightShift,
            Key::RightControl => StringKey::RightControl,
            Key::RightAlt => StringKey::RightAlt,
            Key::RightSuper => StringKey::RightSuper,
            Key::Menu => StringKey::Menu,
            Key::Unknown => StringKey::Unknown,
        }
    }
}

impl Into<Key> for StringKey {
    fn into(self) -> Key {
        match self {
            StringKey::Space => Key::Space,
            StringKey::Apostrophe => Key::Apostrophe,
            StringKey::Comma => Key::Comma,
            StringKey::Minus => Key::Minus,
            StringKey::Period => Key::Period,
            StringKey::Slash => Key::Slash,
            StringKey::Num0 => Key::Num0,
            StringKey::Num1 => Key::Num1,
            StringKey::Num2 => Key::Num2,
            StringKey::Num3 => Key::Num3,
            StringKey::Num4 => Key::Num4,
            StringKey::Num5 => Key::Num5,
            StringKey::Num6 => Key::Num6,
            StringKey::Num7 => Key::Num7,
            StringKey::Num8 => Key::Num8,
            StringKey::Num9 => Key::Num9,
            StringKey::Semicolon => Key::Semicolon,
            StringKey::Equal => Key::Equal,
            StringKey::A => Key::A,
            StringKey::B => Key::B,
            StringKey::C => Key::C,
            StringKey::D => Key::D,
            StringKey::E => Key::E,
            StringKey::F => Key::F,
            StringKey::G => Key::G,
            StringKey::H => Key::H,
            StringKey::I => Key::I,
            StringKey::J => Key::J,
            StringKey::K => Key::K,
            StringKey::L => Key::L,
            StringKey::M => Key::M,
            StringKey::N => Key::N,
            StringKey::O => Key::O,
            StringKey::P => Key::P,
            StringKey::Q => Key::Q,
            StringKey::R => Key::R,
            StringKey::S => Key::S,
            StringKey::T => Key::T,
            StringKey::U => Key::U,
            StringKey::V => Key::V,
            StringKey::W => Key::W,
            StringKey::X => Key::X,
            StringKey::Y => Key::Y,
            StringKey::Z => Key::Z,
            StringKey::LeftBracket => Key::LeftBracket,
            StringKey::Backslash => Key::Backslash,
            StringKey::RightBracket => Key::RightBracket,
            StringKey::GraveAccent => Key::GraveAccent,
            StringKey::World1 => Key::World1,
            StringKey::World2 => Key::World2,
            StringKey::Escape => Key::Escape,
            StringKey::Enter => Key::Enter,
            StringKey::Tab => Key::Tab,
            StringKey::Backspace => Key::Backspace,
            StringKey::Insert => Key::Insert,
            StringKey::Delete => Key::Delete,
            StringKey::Right => Key::Right,
            StringKey::Left => Key::Left,
            StringKey::Down => Key::Down,
            StringKey::Up => Key::Up,
            StringKey::PageUp => Key::PageUp,
            StringKey::PageDown => Key::PageDown,
            StringKey::Home => Key::Home,
            StringKey::End => Key::End,
            StringKey::CapsLock => Key::CapsLock,
            StringKey::ScrollLock => Key::ScrollLock,
            StringKey::NumLock => Key::NumLock,
            StringKey::PrintScreen => Key::PrintScreen,
            StringKey::Pause => Key::Pause,
            StringKey::F1 => Key::F1,
            StringKey::F2 => Key::F2,
            StringKey::F3 => Key::F3,
            StringKey::F4 => Key::F4,
            StringKey::F5 => Key::F5,
            StringKey::F6 => Key::F6,
            StringKey::F7 => Key::F7,
            StringKey::F8 => Key::F8,
            StringKey::F9 => Key::F9,
            StringKey::F10 => Key::F10,
            StringKey::F11 => Key::F11,
            StringKey::F12 => Key::F12,
            StringKey::F13 => Key::F13,
            StringKey::F14 => Key::F14,
            StringKey::F15 => Key::F15,
            StringKey::F16 => Key::F16,
            StringKey::F17 => Key::F17,
            StringKey::F18 => Key::F18,
            StringKey::F19 => Key::F19,
            StringKey::F20 => Key::F20,
            StringKey::F21 => Key::F21,
            StringKey::F22 => Key::F22,
            StringKey::F23 => Key::F23,
            StringKey::F24 => Key::F24,
            StringKey::F25 => Key::F25,
            StringKey::Kp0 => Key::Kp0,
            StringKey::Kp1 => Key::Kp1,
            StringKey::Kp2 => Key::Kp2,
            StringKey::Kp3 => Key::Kp3,
            StringKey::Kp4 => Key::Kp4,
            StringKey::Kp5 => Key::Kp5,
            StringKey::Kp6 => Key::Kp6,
            StringKey::Kp7 => Key::Kp7,
            StringKey::Kp8 => Key::Kp8,
            StringKey::Kp9 => Key::Kp9,
            StringKey::KpDecimal => Key::KpDecimal,
            StringKey::KpDivide => Key::KpDivide,
            StringKey::KpMultiply => Key::KpMultiply,
            StringKey::KpSubtract => Key::KpSubtract,
            StringKey::KpAdd => Key::KpAdd,
            StringKey::KpEnter => Key::KpEnter,
            StringKey::KpEqual => Key::KpEqual,
            StringKey::LeftShift => Key::LeftShift,
            StringKey::LeftControl => Key::LeftControl,
            StringKey::LeftAlt => Key::LeftAlt,
            StringKey::LeftSuper => Key::LeftSuper,
            StringKey::RightShift => Key::RightShift,
            StringKey::RightControl => Key::RightControl,
            StringKey::RightAlt => Key::RightAlt,
            StringKey::RightSuper => Key::RightSuper,
            StringKey::Menu => Key::Menu,
            StringKey::Unknown => Key::Unknown,
        }
    }
}
